name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  # ✅ 合并后的 CI + Docker 构建 + 推送
  build-test-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [mall-admin, mall-auth, mall-gateway, mall-monitor, mall-portal, mall-search]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test
        run: mvn clean install -pl ${{ matrix.service }} -am

      #      - name: SonarCloud Scan
      #        uses: SonarSource/sonarcloud-github-action@v2
      #        with:
      #          projectBaseDir: ${{ matrix.service }}
      #        env:
      #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

  # ☁️ CD 阶段：远程部署
  deploy-to-gcp:
    needs: build-test-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: mall-admin
            script: scripts/deploy-mall-admin.sh
          - service: mall-auth
            script: scripts/deploy-mall-auth.sh
          - service: mall-gateway
            script: scripts/deploy-mall-gateway.sh
          - service: mall-monitor
            script: scripts/deploy-mall-monitor.sh
          - service: mall-portal
            script: scripts/deploy-mall-portal.sh
          - service: mall-search
            script: scripts/deploy-mall-search.sh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read script content
        id: read_script
        run: |
          echo "SCRIPT_CONTENT<<EOF" >> $GITHUB_OUTPUT
          cat ${{ matrix.script }} >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload & Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          envs: DOCKER_IMAGE
          script: |
            cat >/tmp/deploy-${{ matrix.service }}.sh <<'EOF'
            ${{ steps.read_script.outputs.SCRIPT_CONTENT }}
            EOF
            chmod +x /tmp/deploy-${{ matrix.service }}.sh
            bash /tmp/deploy-${{ matrix.service }}.sh
